try to fix issue of "unhashable type: 'list'"
```scientist = sosia.Original(57203012240, 1988, year_margin=1, coauth_margin=0.1, pub_margin=0.1)```

```scientist.define_search_group(verbose=True, stacked=True)               # Authors publishing in pre-defined treat_scientist-mouse_sources
print(scientist.search_group)
C:\anaconda3\lib\site-packages\sqlalchemy\engine\result.py:182: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence
Searching authors for search_group in 153 sources...
Searching authors in 153 sources in 1988...
Progress: |██████████████████████████████████████████████████| 100.00% Complete
Traceback (most recent call last):

  File "<ipython-input-5-72858bd4cdcd>", line 1, in <module>
    scientist.define_search_group(verbose=True, stacked=True)               # Authors publishing in pre-defined treat_scientist-mouse_sources

  File "C:\anaconda3\lib\site-packages\sosia\sosia.py", line 185, in define_search_group
    query_year(y, _sources_search, refresh, verbose)

  File "C:\anaconda3\lib\site-packages\sosia\processing\queries.py", line 146, in query_year
    .apply(get_auth_from_df)

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 701, in apply
    return self._python_apply_general(f)

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\groupby.py", line 707, in _python_apply_general
    self.axis)

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 166, in apply
    splitter = self._get_splitter(data, axis=axis)

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 149, in _get_splitter
    comp_ids, _, ngroups = self.group_info

  File "pandas\_libs\properties.pyx", line 36, in pandas._libs.properties.CachedProperty.__get__

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 252, in group_info
    comp_ids, obs_group_ids = self._get_compressed_labels()

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in _get_compressed_labels
    all_labels = [ping.labels for ping in self.groupings]

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\ops.py", line 268, in <listcomp>
    all_labels = [ping.labels for ping in self.groupings]

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 367, in labels
    self._make_labels()

  File "C:\anaconda3\lib\site-packages\pandas\core\groupby\grouper.py", line 392, in _make_labels
    self.grouper, sort=self.sort)

  File "C:\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 188, in wrapper
    return func(*args, **kwargs)

  File "C:\anaconda3\lib\site-packages\pandas\core\algorithms.py", line 613, in factorize
    na_value=na_value)

  File "C:\anaconda3\lib\site-packages\pandas\core\algorithms.py", line 460, in _factorize_array
    na_value=na_value)

  File "pandas\_libs\hashtable_class_helper.pxi", line 1792, in pandas._libs.hashtable.PyObjectHashTable.factorize

  File "pandas\_libs\hashtable_class_helper.pxi", line 1712, in pandas._libs.hashtable.PyObjectHashTable._unique

TypeError: unhashable type: 'list'```